import path from 'path';

const extensionLanguageMap = new Map<string, string>([
  ['.ts', 'typescript'],
  ['.tsx', 'typescript'],
  ['.js', 'javascript'],
  ['.jsx', 'javascript'],
  ['.mjs', 'javascript'],
  ['.cjs', 'javascript'],
  ['.java', 'java'],
  ['.py', 'python'],
  ['.pyw', 'python'],
  ['.go', 'go'],
  ['.rs', 'rust'],
  ['.cs', 'csharp'],
  ['.cpp', 'cpp'],
  ['.cc', 'cpp'],
  ['.cxx', 'cpp'],
  ['.hpp', 'cpp'],
  ['.hh', 'cpp'],
  ['.hxx', 'cpp'],
  ['.c', 'c'],
  ['.h', 'c'],
  ['.rb', 'ruby'],
  ['.php', 'php'],
  ['.swift', 'swift'],
  ['.kt', 'kotlin'],
  ['.kts', 'kotlin'],
  ['.scala', 'scala'],
  ['.sc', 'scala'],
  ['.dart', 'dart'],
  ['.lua', 'lua'],
  ['.r', 'r'],
  ['.R', 'r'],
  ['.m', 'objective-c'],
  ['.mm', 'objective-cpp'],
  ['.ex', 'elixir'],
  ['.exs', 'elixir'],
  ['.erl', 'erlang'],
  ['.hrl', 'erlang'],
  ['.fs', 'fsharp'],
  ['.fsx', 'fsharp'],
  ['.clj', 'clojure'],
  ['.cljs', 'clojure'],
  ['.cljc', 'clojure'],
  ['.hs', 'haskell'],
  ['.lhs', 'haskell'],
  ['.ml', 'ocaml'],
  ['.mli', 'ocaml'],
  ['.nim', 'nim'],
  ['.zig', 'zig'],
  ['.jl', 'julia'],
  ['.pl', 'perl'],
  ['.pm', 'perl'],
  ['.sh', 'shell'],
  ['.bash', 'shell'],
  ['.zsh', 'shell'],
  ['.fish', 'shell'],
  ['.ps1', 'powershell'],
  ['.psm1', 'powershell'],
  ['.sql', 'sql'],
  ['.html', 'html'],
  ['.htm', 'html'],
  ['.css', 'css'],
  ['.scss', 'scss'],
  ['.sass', 'sass'],
  ['.less', 'less'],
  ['.vue', 'vue'],
  ['.svelte', 'svelte'],
  ['.astro', 'astro'],
  ['.json', 'json'],
  ['.jsonc', 'jsonc'],
  ['.yaml', 'yaml'],
  ['.yml', 'yaml'],
  ['.toml', 'toml'],
  ['.xml', 'xml'],
  ['.txt', 'text'],
  ['.md', 'markdown'],
  ['.mdx', 'mdx'],
  ['.dockerfile', 'dockerfile'],
  ['.tf', 'terraform'],
  ['.tfvars', 'terraform'],
  ['.proto', 'protobuf'],
  ['.graphql', 'graphql'],
  ['.gql', 'graphql'],
  // Multi-modal formats
  ['.pdf', 'pdf'],
]);

const basenameLanguageMap = new Map<string, string>([
  ['dockerfile', 'dockerfile'],
  ['makefile', 'make'],
  ['rakefile', 'ruby'],
  ['gemfile', 'ruby'],
  ['jenkinsfile', 'groovy'],
  ['.eslintrc', 'eslint'],
  ['.gitignore', 'gitignore'],
  ['requirements.txt', 'python-requirements'],
]);

export function detectLanguage(filePath: string): string {
  const baseName = path.basename(filePath);
  const lowerBaseName = baseName.toLowerCase();
  const baseMatch = basenameLanguageMap.get(lowerBaseName);
  if (baseMatch) return baseMatch;

  const ext = path.extname(filePath);
  return extensionLanguageMap.get(ext) || extensionLanguageMap.get(ext.toLowerCase()) || 'unknown';
}
